# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_c215e2372ab6_key -iv $encrypted_c215e2372ab6_iv
  -in projeto01gaby-23a03732798b.json.enc -out ../directed-cove-314122-7ae0c53644cd.json
  -d

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-fabaugsilv
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab-fabaugsilv.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile:  ../directed-cove-314122-7ae0c53644cd.json
        project: directed-cove-314122
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://directed-cove-314122.uc.r.appspot.com/ | grep Hello || travis_terminate 1;

